### ISSUE TITLE
Example in documentation

### ISSUE THREAD

**Issue by joepio** [ryankurte/action-mdbook#1]
Hi there Ryan,

Thanks for creating this! I'm having some problems getting in working in my repo. 

Here's the [blank.yml](https://github.com/ontola/atomic-data/blob/master/.github/workflows/blank.yml) that contains the github action.

The actions seems to be running correctly, but I don't know what should happen next. I kind of assumed the action would commit the generated HTML to some side branch, and I could refer to that branch in my github pages settings, but no commits are made. I must be missing something.

Maybe extend the docs a little?

**Comment by ryankurte** [comment]
Hey thanks for the feedback!

The action only builds the book, because, who knows what people might want to do with it, so as you've determined you also need a step to publish the outputs. I'm not sure why your example is not working, does it have the correct credentials?

I'm using it with [crazy-max/ghaction-github-pages](https://github.com/crazy-max/ghaction-github-pages) in the following configuration:

``` yaml
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Generate mdbook
      uses: ryankurte/action-mdbook@0.1.1
    - name: Publish to GH Pages
      uses: crazy-max/ghaction-github-pages@v1.2.4
      with:
        build_dir: book
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

And I can either put this in the docs, or would be happy to accept a PR when you get it working.
